### ISSUE TITLE
GDPR consent management not working on v22

### ISSUE THREAD

**Issue by yuripave** [PubMatic/OpenWrap#264]
In v22 of the OpenWrap, the prebid `consentManagment` config did not pass correctly:
https://github.com/PubMatic/OpenWrap/blob/4c9b89b42b1f97a92e148dd0eafc54c2f3f17c33/src_new/adapters/prebid.js#L725-L729

It should passed as `consentManagment.gdpr` according to [prebid docs](https://docs.prebid.org/dev-docs/modules/consentManagement.html#page-integration), and it was correct in v21
https://github.com/PubMatic/OpenWrap/blob/707164ac7493a23188d1cbd43ec17799086c36ab/src_new/adapters/prebid.js#L702-L707

**Comment by pm-shashank-jain** [comment]
Thanks for raising the issue, it was changed in code refactor, but will **NOT** have any issues as prebid consent management has backward compatibility(Ref-> https://github.com/prebid/Prebid.js/blob/71d75c4f212995ec49e9928f59ff19ee539a8b31/modules/consentManagement.js#L476 ).
We have updated the code and it will be fixed in next release.

**Comment by yuripave** [comment]
Thanks for the update. I am aware of the prebid.js backward compatible logic but it will not work when usp is also defined in the config as that code will read from config.gdpr if config.ups is also defined.

**Comment by pm-shashank-jain** [comment]
Agreed!, it will return an warning and that is correct as for USP gdpr should not be considered. But USP will work as it has different module altogether. Ref-> https://github.com/prebid/Prebid.js/blob/master/modules/consentManagementUsp.js

**Comment by pm-shashank-jain** [comment]
The only case that won't work if both USP and GDPR have to be defined.
